apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gonella
  namespace: argocd
spec:
  secretName: wildcard-gonella-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.gonella.co.uk"