apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  commonName: argocd.gonella.co.uk
  dnsNames:
    - argocd.gonella.co.uk
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer